// GENERATED by scripts/sync-edge-domain.mjs from packages/domain/src/receipt-evidence.ts. Do not edit.

// Evidence helpers shared by the web manual-JSON validator and the
// process-receipt-imports Edge Function. The Edge copy is generated by
// scripts/sync-edge-domain.mjs, so this file may import only from ./money.
import { roundMoney, roundQty } from './money.ts';

export type AccountingLine = {
  product_name: string;
  qty: number;
  unit_price_orig: number;
  discount_orig?: number | undefined;
};

type PairPass = 'cancellation' | 'discount';

const INVISIBLE_CHARS = /[\u200B-\u200D\uFEFF]/g;

export function normalizeReceiptText(value: string): string {
  return value
    .normalize('NFKC')
    .replace(INVISIBLE_CHARS, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

export function amountAppearsInText(text: string, amount: number): boolean {
  const absolute = Math.abs(roundMoney(amount)).toFixed(2);
  const variants = [absolute, absolute.replace('.', ',')];
  const compactText = text.replace(/\s/g, '');
  return variants.some((variant) => compactText.includes(variant));
}

export function integerAppearsInText(text: string, value: number): boolean {
  return new RegExp(String.raw`(?:^|\D)${String(value)}(?:\D|$)`, 'u').test(text);
}

export function hasExplicitMultiplier(text: string, qty: number): boolean {
  const rawQty = String(roundQty(qty)).replace('.', '[.,]');
  const quantityPattern = new RegExp(
    String.raw`(?:^|\s)(?:${rawQty}\s*(?:x|×|stk\.?|st\.?|pcs)|(?:x|×)\s*${rawQty})(?:\s|$)`,
    'iu',
  );
  return quantityPattern.test(text);
}

export function hasWeightOrVolume(text: string): boolean {
  return /(?:^|\s)\d+(?:[.,]\d+)?\s*(?:kg|g|l|ml)(?:\s|$)/iu.test(text);
}

/** Cancellation pairs first, then partial discounts; returns a new array. */
export function mergeAccountingPairs<T extends AccountingLine>(items: T[]): T[] {
  const result = items.map((item) => ({ ...item }));
  const removed = new Set<number>();
  const groups = groupItemIndices(result);

  for (const indices of groups.values()) {
    const positives = indices.filter((index) => isSignedPrice(result[index], 1));
    const negatives = indices.filter((index) => isSignedPrice(result[index], -1));
    const claimed = new Set<number>();

    // Exact cancellations must claim first; otherwise a cancellation could be
    // consumed as a partial discount. Both passes share the same claimed set.
    claimPairPass(result, positives, negatives, claimed, removed, 'cancellation');
    claimPairPass(result, positives, negatives, claimed, removed, 'discount');
  }
  return result.filter((_, index) => !removed.has(index));
}

function groupItemIndices(items: AccountingLine[]): Map<string, number[]> {
  const groups = new Map<string, number[]>();
  items.forEach((item, index) => {
    const key = normalizeReceiptText(item.product_name);
    if (!key) return;
    const indices = groups.get(key);
    if (indices) indices.push(index);
    else groups.set(key, [index]);
  });
  return groups;
}

function claimPairPass(
  items: AccountingLine[],
  positiveIndices: number[],
  negativeIndices: number[],
  claimed: Set<number>,
  removed: Set<number>,
  pass: PairPass,
): void {
  for (const negativeIndex of negativeIndices) {
    if (claimed.has(negativeIndex)) continue;
    const negative = items[negativeIndex];
    if (!negative) continue;
    const positiveIndex = positiveIndices.find((candidateIndex) =>
      isPairCandidate(items[candidateIndex], negative, claimed.has(candidateIndex), pass),
    );
    if (positiveIndex === undefined) continue;
    const positive = items[positiveIndex];
    if (!positive) continue;

    claimed.add(positiveIndex);
    claimed.add(negativeIndex);
    removed.add(negativeIndex);
    if (pass === 'cancellation') {
      positive.unit_price_orig = 0;
      positive.discount_orig = 0;
    } else {
      positive.discount_orig = roundMoney(Math.abs(negative.unit_price_orig));
    }
  }
}

function isPairCandidate(
  positive: AccountingLine | undefined,
  negative: AccountingLine,
  alreadyClaimed: boolean,
  pass: PairPass,
): boolean {
  if (!positive || alreadyClaimed || Math.abs(positive.qty - negative.qty) > 0.001) return false;
  const positiveTotal = grossLineTotal(positive);
  const negativeTotal = grossLineTotal(negative);
  return pass === 'cancellation' ? positiveTotal === negativeTotal : positiveTotal > negativeTotal;
}

function grossLineTotal(item: AccountingLine): number {
  return roundMoney(Math.abs(item.qty * item.unit_price_orig));
}

function isSignedPrice(item: AccountingLine | undefined, sign: 1 | -1): boolean {
  return sign * (item?.unit_price_orig ?? 0) > 0;
}
