import assert from 'node:assert/strict';

export function inventoryNames(markdown) {
  const body = markdown.slice(
    markdown.indexOf('## Pfand'),
    markdown.indexOf('## Unlinked historical item names'),
  );
  return body
    .split(/\r?\n/)
    .filter((line) => line.startsWith('- '))
    .map((line) => line.slice(2).replace(/\s+_\(has an unlinked historical line\)_$/, ''));
}

export const normalizeName = (name) => name.trim().replace(/\s+/gu, ' ').toLowerCase();

export function rawNames(display) {
  const parts = display.split(' / ');
  // Slash is also literal text (Feta / Schafskäse). Split only the inventory's
  // case-only collision groups, never distinct product descriptions.
  return parts.every((part) => normalizeName(part) === normalizeName(parts[0])) ? parts : [display];
}

export function validateCatalog(catalog, assignments, expectedNames) {
  const validateLabels = (rows) => {
    const ids = new Set();
    for (const row of rows) {
      assert.match(row.id, /^[a-z][a-z0-9_]*$/);
      assert(!ids.has(row.id), `Duplicate ID: ${row.id}`);
      ids.add(row.id);
      for (const field of ['name_uk', 'name_en', 'name_de']) {
        assert(typeof row[field] === 'string' && row[field].trim(), `${row.id}: missing ${field}`);
        assert(/\p{L}/u.test(row[field]), `${row.id}: ${field} must contain a readable label`);
      }
      assert(
        Array.isArray(row.aliases) &&
          row.aliases.every((alias) => typeof alias === 'string' && alias.trim()),
        `${row.id}: invalid aliases`,
      );
    }
    return ids;
  };
  const families = validateLabels(catalog.families);
  validateLabels(catalog.variants);
  const variants = new Map(catalog.variants.map((variant) => [variant.id, variant]));
  for (const variant of variants.values())
    assert(families.has(variant.family_id), `${variant.id}: missing parent`);
  const seen = new Set();
  const expected = new Set(expectedNames);
  assert.equal(expected.size, expectedNames.length, 'Duplicate source inventory names');
  for (const assignment of assignments) {
    assert(expected.has(assignment.source_name), `Unexpected source: ${assignment.source_name}`);
    assert(!seen.has(assignment.source_name), `Duplicate source: ${assignment.source_name}`);
    seen.add(assignment.source_name);
    assert(['ready', 'review', 'excluded'].includes(assignment.status));
    const family = assignment.product_family_id;
    const variant = assignment.product_variant_id;
    assert(family === null || families.has(family), `Unknown family: ${assignment.source_name}`);
    assert(
      variant === null || variants.get(variant)?.family_id === family,
      `Invalid variant: ${assignment.source_name}`,
    );
    if (assignment.status === 'ready')
      assert(family !== null, `Ready without family: ${assignment.source_name}`);
    else
      assert(
        typeof assignment.reason === 'string' && assignment.reason.trim(),
        `Missing review reason: ${assignment.source_name}`,
      );
    assert(
      assignment.brand === null ||
        (typeof assignment.brand === 'string' && assignment.brand.trim()),
    );
    assert(assignment.is_organic === null || typeof assignment.is_organic === 'boolean');
  }
  assert.deepEqual([...seen].sort(), [...expected].sort(), 'Incomplete inventory coverage');
  return Object.fromEntries(
    ['ready', 'review', 'excluded'].map((status) => [
      status,
      assignments.filter((row) => row.status === status).length,
    ]),
  );
}

const sql = (value) =>
  value === null
    ? 'null'
    : typeof value === 'boolean'
      ? String(value)
      : `'${value.replaceAll("'", "''")}'`;
const textArray = (values) => `array[${values.map(sql).join(', ')}]::text[]`;

export function seedSql(catalog, assignments) {
  const rows = [];
  for (const row of assignments.filter((entry) => entry.status === 'ready')) {
    for (const source of new Set(rawNames(row.source_name).map(normalizeName))) {
      rows.push(
        `(${[source, row.product_family_id, row.product_variant_id, row.brand, row.is_organic].map(sql).join(', ')})`,
      );
    }
  }
  return `-- Generated by scripts/product-taxonomy/prepare.mjs. Review the source JSON first.
-- Only ready assignments; existing classifications and original receipt text are preserved.
begin;

insert into public.product_families (id, name_uk, name_en, name_de, aliases) values
${catalog.families.map((row) => `(${[row.id, row.name_uk, row.name_en, row.name_de].map(sql).join(', ')}, ${textArray(row.aliases)})`).join(',\n')}
on conflict (id) do nothing;

insert into public.product_variants (id, family_id, name_uk, name_en, name_de, aliases) values
${catalog.variants.map((row) => `(${[row.id, row.family_id, row.name_uk, row.name_en, row.name_de].map(sql).join(', ')}, ${textArray(row.aliases)})`).join(',\n')}
on conflict (id) do nothing;

create temporary table taxonomy_assignment (
  source_name text primary key, family_id text not null, variant_id text,
  brand text, is_organic boolean
) on commit drop;
insert into taxonomy_assignment values
${rows.join(',\n')};

update public.products p
set product_family_id = a.family_id, product_variant_id = a.variant_id,
    brand = coalesce(p.brand, a.brand), is_organic = coalesce(p.is_organic, a.is_organic)
from taxonomy_assignment a
where lower(regexp_replace(btrim(p.name), '\\s+', ' ', 'g')) = a.source_name
  and p.product_family_id is null and p.product_variant_id is null;

update public.items i
set product_family_id = a.family_id, product_variant_id = a.variant_id
from taxonomy_assignment a
where lower(regexp_replace(btrim(i.product_name), '\\s+', ' ', 'g')) = a.source_name
  and i.product_family_id is null and i.product_variant_id is null
  and i.total_orig > 0;

commit;
`;
}
