// Single Supabase JS client instance.
//
// IMPORTANT: this module is private to adapters in `web/src/shared/lib/<area>/`
// and feature `api/` folders. ESLint enforces this via `no-restricted-imports`
// (see web/eslint.config.js). Never import from a route, page, or component —
// go through the relevant port (authService / photoStorage / fxRateProvider /
// parseReceiptService) exported from `@/shared/lib/dependencies`.
//
// The typed `Database` import is generated by `supabase gen types typescript
// --linked` after `supabase link`. Until that runs, the type is `unknown`
// (graceful degradation — queries still work, just less safe).

import { createClient } from '@supabase/supabase-js';
import { env } from './env';
import type { Database } from '@/shared/types/database.types';

export const supabase = createClient<Database>(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

export type SupabaseClientInstance = typeof supabase;
